[package]
name = "forge"
version = "0.1.0"
authors = ["nokaa <nokaa@cock.li>"]

[dependencies]
clap = "2.1.2"
rotor = "0.6.2"
fe-rustty = { git = "https://github.com/Syntaf/fe-rustty.git" }

[dev-dependencies]
argparse = "0.2.1"
nix = "0.4.2"
void = "1.0.0"
